
import co.edu.unicesar.vista.GUI_Consulta;
import co.edu.unicesar.vista.GUI_Registro;
import java.io.File;
import java.io.FileWriter;
import java.io.FileReader;
import static java.nio.file.Files.list;
import static java.util.Collections.list;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class GUI_Inicio extends javax.swing.JFrame {
    DefaultTableModel modelo;
    

    /**
     * Creates new form GUI_Inicio
     */
    public GUI_Inicio() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        model=(DefaultTableModel)this.jTabladatos.getModel();
        JOptionPane.showMessageDialog(null, "TUTORIAL \n Para ingresar datos debe primero darle al boton agregar y luego introduce los datos en la tabla y le da al boton guardar.\n Para borrar, le da al boton borrar y escribe la fila de datos que quiere borrar y le da al final guardar.\n Si quiere abrir tiene que guardar primero datos en la tabla y luego se sale del programa y vuelve a entrar y le da abrir.");
    }
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTabladatos = new javax.swing.JTable();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAbrir = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        JImagen = new javax.swing.JLabel();
        jLabelImagen2 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jScrollPane5.setViewportView(jEditorPane1);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(33, 33, 33));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabladatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Idbn", "Titulo", "Autor", "Año", "Costo", "Paginas", "Edicion", "Duracion", "Formato"
            }
        ));
        jTabladatos.setGridColor(new java.awt.Color(0, 0, 0));
        jTabladatos.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jTabladatos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTabladatos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabladatosAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(jTabladatos);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 580, 340));

        jButtonAgregar.setBackground(new java.awt.Color(20, 255, 236));
        jButtonAgregar.setForeground(new java.awt.Color(33, 33, 33));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 75, -1));

        jButtonEliminar.setBackground(new java.awt.Color(20, 255, 236));
        jButtonEliminar.setForeground(new java.awt.Color(33, 33, 33));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 75, -1));

        jButtonAbrir.setBackground(new java.awt.Color(20, 255, 236));
        jButtonAbrir.setForeground(new java.awt.Color(33, 33, 33));
        jButtonAbrir.setText("Abrir");
        jButtonAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jButtonGuardar.setBackground(new java.awt.Color(20, 255, 236));
        jButtonGuardar.setForeground(new java.awt.Color(33, 33, 33));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabelTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(102, 255, 255));
        jLabelTitulo.setText("Registro de libros y Audio Libros");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        JImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/kisspng-clip-art-line-art-portable-network-graphics-free-c-book-transparent-free-clipart-clipart-finders-5cc1f1a93d5c44.4229557815562141852513.png"))); // NOI18N
        getContentPane().add(JImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 130, 100));

        jLabelImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pngwing.com (1).png"))); // NOI18N
        getContentPane().add(jLabelImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 140, 100));

        jButtonSalir.setBackground(new java.awt.Color(0, 153, 153));
        jButtonSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(33, 33, 33));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 70, 30));

        jLabelFondo.setBackground(new java.awt.Color(0, 0, 0));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/4-min.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        model.addRow(new Object[]{"",""});
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        try {
            FileWriter salvar = new FileWriter("Registro.pb");
            for (int i = 0; i < this.jTabladatos.getRowCount(); i++) {
                salvar.write(model.getValueAt(i, 0).toString()+"\n");
                salvar.write(model.getValueAt(i, 1).toString()+"\n");
                salvar.write(model.getValueAt(i, 2).toString()+"\n");
                salvar.write(model.getValueAt(i, 3).toString()+"\n");
                salvar.write(model.getValueAt(i, 4).toString()+"\n");
                salvar.write(model.getValueAt(i, 5).toString()+"\n");
                salvar.write(model.getValueAt(i, 6).toString()+"\n");
                salvar.write(model.getValueAt(i, 7).toString()+"\n");
                salvar.write(model.getValueAt(i, 8).toString()+"\n");
                salvar.write(model.getValueAt(i, 9).toString()+"\n");
            }
            salvar.close();
            JOptionPane.showMessageDialog(null, "Datos Guardados");
        } catch (Exception x) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTabladatosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabladatosAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabladatosAncestorAdded

    private void jButtonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirActionPerformed
        String Idbn,Titulo,Autor,Año,Costo,Paginas,Edicion,Duracion,Formato;
        String au = "Registro.pb";
        Scanner linea = null;
        File doc_le = new File(au);
        try {
            linea = new Scanner(doc_le);
            while (linea.hasNextLine()) {                
                Idbn = linea.nextLine();
                Titulo = linea.nextLine();
                Autor = linea.nextLine();
                Año = linea.nextLine();
                Costo = linea.nextLine();
                Paginas = linea.nextLine();
                Edicion = linea.nextLine();
                Duracion = linea.nextLine();
                Formato = linea.nextLine();
                model.addRow(new Object[]{Idbn,Titulo,Autor,Año,Costo,Paginas,Edicion,Duracion,Formato});
                
            }
        } catch (Exception x) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }//GEN-LAST:event_jButtonAbrirActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        String dato = JOptionPane.showInputDialog("Ingrese cuantas filas quiere borrar \n Ingrese 0 para borrar la primera publicacion (fila), 1 para la segunda publicacion y asi suceisvamente");
        int numero = Integer.parseInt(dato);
        model.removeRow(numero);
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        new GUI_Registro(this, true);
    }  
    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        new GUI_Consulta(this, true);
    }  
    
     private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
         System.exit(0);
    } 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Inicio().setVisible(true);
            }
        });
    }
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JImagen;
    private javax.swing.JButton jButtonAbrir;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelImagen2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTabladatos;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
